### ISSUE TITLE
Problem installing lxml

### ISSUE THREAD

**Issue by G3K45** [termux/termux-packages#18579]
### Problem description

I am going to install lxml for a tool I need to use and take this error
```
Collecting lxml
  Using cached lxml-4.9.3.tar.gz (3.6 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [174 lines of output]
      Building lxml version 4.9.3.
      /data/data/com.termux/files/usr/tmp/pip-install-dns92bfc/lxml_8be6a95f795443dcb76ce90a34da4f2c/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building without Cython.
      Building against libxml2 2.12.1 and libxslt 1.1.39
      Building against libxml2/libxslt in the following directory: /data/data/com.termux/files/usr/lib
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/ElementInclude.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/__init__.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/_elementpath.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/builder.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/cssselect.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/doctestcompare.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/sax.py -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/usedoctest.py -> build/lib.linux-aarch64-cpython-311/lxml
      creating build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.linux-aarch64-cpython-311/lxml/includes
      creating build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/builder.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/clean.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/defs.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/diff.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.linux-aarch64-cpython-311/lxml/html
      creating build/lib.linux-aarch64-cpython-311/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/etree_api.h -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/lxml.etree.h -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/etree.pyx -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/objectify.pyx -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/classlookup.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/cleanup.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/debug.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/docloader.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/dtd.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/extensions.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/iterparse.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/objectpath.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/parser.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/proxy.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/public-api.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/relaxng.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/saxparser.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/schematron.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/serializer.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xinclude.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xmlid.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xpath.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xslt.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/xsltext.pxi -> build/lib.linux-aarch64-cpython-311/lxml
      copying src/lxml/includes/__init__.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.linux-aarch64-cpython-311/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.linux-aarch64-cpython-311/lxml/includes
      creating build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources
      creating build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/rng
      creating build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl
      creating build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-aarch64-cpython-311/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/src
      creating build/temp.linux-aarch64-cpython-311/src/lxml
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.11 -c src/lxml/etree.c -o build/temp.linux-aarch64-cpython-311/src/lxml/etree.o -w
      src/lxml/etree.c:113152:38: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       113152 |   __pyx_v_self->_c_ctxt->sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
              |                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:117640:25: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       117640 |     __pyx_v_sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
              |                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:181724:28: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       181724 |   __pyx_v_xpathCtxt->error = __pyx_f_4lxml_5etree__receiveXPathError;
              |                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:218998:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       218998 |   xmlRelaxNGSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/relaxng.h:155:30: note: passing argument to parameter 'serror' here
        155 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:219416:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       219416 |     xmlRelaxNGSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/relaxng.h:184:31: note: passing argument to parameter 'serror' here
        184 |                                           xmlStructuredErrorFunc serror, void *ctx);
            |                                                                  ^
      src/lxml/etree.c:220305:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       220305 |   xmlSchemaSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:156:30: note: passing argument to parameter 'serror' here
        156 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:220848:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       220848 |     xmlSchemaSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
        185 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:221613:66: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       221613 |     xmlSchemaSetValidStructuredErrors(__pyx_v_self->_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_error_log));
              |                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
        185 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:222790:63: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       222790 |     xmlSchematronSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/schematron.h:105:31: note: passing argument to parameter 'serror' here
        105 |                                           xmlStructuredErrorFunc serror,
            |                                                                  ^
      9 errors generated.
      Compile failed: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      creating data
      creating data/data
      creating data/data/com.termux
      creating data/data/com.termux/files
      creating data/data/com.termux/files/usr
      creating data/data/com.termux/files/usr/tmp
      cc -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInitd09ks7k3.c -o data/data/com.termux/files/usr/tmp/xmlXPathInitd09ks7k3.o
      /data/data/com.termux/files/usr/tmp/xmlXPathInitd09ks7k3.c:3:5: warning: 'xmlXPathInit' is deprecated [-Wdeprecated-declarations]
          3 |     xmlXPathInit();
            |     ^
      /data/data/com.termux/files/usr/include/libxml2/libxml/xpath.h:562:1: note: 'xmlXPathInit' has been explicitly marked deprecated here
        562 | XML_DEPRECATED
            | ^
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlversion.h:447:43: note: expanded from macro 'XML_DEPRECATED'
        447 | #    define XML_DEPRECATED __attribute__((deprecated))
            |                                           ^
      1 warning generated.
      cc data/data/com.termux/files/usr/tmp/xmlXPathInitd09ks7k3.o -L/data/data/com.termux/files/usr/lib -lxml2 -o a.out
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
ERROR: Could not build wheels for lxml, which is required to install pyproject.toml-based projects
```

### System information
```
termux-info:

TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=21432
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.5
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Tue May 17 14:53:43 CST 2022 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
AQM-LX1
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by twaik** [comment]
Use `CFLAGS="-Wno-error=incompatible-function-pointer-types" pip3 install lxml` as a temporary workaround.

**Comment by twaik** [comment]
It is not fixed. The solution I've posted is a workaround.

**Comment by licy183** [comment]
This issue cannot be `fixed` on our side. `pip` always fetches source tarball. It must be resolved upstream, by either lxml or Cython.

**Comment by truboxl** [comment]
This is supposedly fixed in lxml-5.0.0 and should be closed

https://github.com/lxml/lxml/commit/b0861bea17769584a85f57eb00235ce0ca9811af

**Comment by truboxl** [comment]
No longer reproducible with `pip install lxml` 5.1.0. Closing.

**Comment by Suletta-Majo** [comment]
This is a resolved topic, but I think it's the same error, so I'd like to report it and ask a question.  
I installed both `libxml2` and `libxslt` by reading below issue thread.  
https://github.com/termux/termux-packages/issues/3793
I also installed `pkg install python-lxml` by reading here.  
But I still can't install it, please let me know if there is any solution.  

```
~$ pip install dlna-cast

Collecting dlna-cast
  Using cached dlna_cast-0.1.8-py3-none-any.whl.metadata (4.8 kB)
Collecting fire<0.5.0,>=0.4.0 (from dlna-cast)
  Using cached fire-0.4.0-py2.py3-none-any.whl
Collecting python-dotenv<0.22.0,>=0.21.0 (from python-dotenv[cli]<0.22.0,>=0.21.0->dlna-cast)
  Using cached python_dotenv-0.21.1-py3-none-any.whl.metadata (21 kB)
Collecting upnpclient<2.0.0,>=1.0.3 (from dlna-cast)
  Using cached upnpclient-1.0.3-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: six in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from fire<0.5.0,>=0.4.0->dlna-cast) (1.16.0)
Collecting termcolor (from fire<0.5.0,>=0.4.0->dlna-cast)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: click>=5.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from python-dotenv[cli]<0.22.0,>=0.21.0->dlna-cast) (8.1.7)
Collecting ifaddr<0.2.0,>=0.1.7 (from upnpclient<2.0.0,>=1.0.3->dlna-cast)
  Using cached ifaddr-0.1.7-py2.py3-none-any.whl.metadata (3.9 kB)
Collecting lxml<5.0.0,>=4.0.0 (from upnpclient<2.0.0,>=1.0.3->dlna-cast)
  Using cached lxml-4.9.4.tar.gz (3.6 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: python-dateutil<3.0.0,>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from upnpclient<2.0.0,>=1.0.3->dlna-cast) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from upnpclient<2.0.0,>=1.0.3->dlna-cast) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->upnpclient<2.0.0,>=1.0.3->dlna-cast) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->upnpclient<2.0.0,>=1.0.3->dlna-cast) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->upnpclient<2.0.0,>=1.0.3->dlna-cast) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from requests<3.0.0,>=2.0.0->upnpclient<2.0.0,>=1.0.3->dlna-cast) (2024.8.30)
Using cached dlna_cast-0.1.8-py3-none-any.whl (31 kB)
Using cached python_dotenv-0.21.1-py3-none-any.whl (19 kB)
Using cached upnpclient-1.0.3-py3-none-any.whl (18 kB)
Using cached ifaddr-0.1.7-py2.py3-none-any.whl (10 kB)
Using cached termcolor-2.5.0-py3-none-any.whl (7.8 kB)
Building wheels for collected packages: lxml
  Building wheel for lxml (setup.py): started
  Building wheel for lxml (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [166 lines of output]
      Building lxml version 4.9.4.
      /data/data/com.termux/files/usr/tmp/pip-install-hiwe6291/lxml_4a809a9042074488945b115561f693a1/setup.py:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building without Cython.
      Building against libxml2 2.13.4 and libxslt 1.1.42
      Building against libxml2/libxslt in one of the following directories:
        /data/data/com.termux/files/usr/lib
        /data/data/com.termux/files/usr//data/data/com.termux/files/usr/lib
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/ElementInclude.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/__init__.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/_elementpath.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/builder.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/cssselect.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/doctestcompare.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/sax.py -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/usedoctest.py -> build/lib.linux-aarch64-cpython-312/lxml
      creating build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.linux-aarch64-cpython-312/lxml/includes
      creating build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/builder.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/clean.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/defs.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/diff.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.linux-aarch64-cpython-312/lxml/html
      creating build/lib.linux-aarch64-cpython-312/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/etree_api.h -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/lxml.etree.h -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/etree.pyx -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/objectify.pyx -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/classlookup.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/cleanup.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/debug.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/docloader.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/dtd.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/extensions.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/iterparse.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/objectpath.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/parser.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/proxy.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/public-api.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/relaxng.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/saxparser.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/schematron.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/serializer.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xinclude.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xmlid.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xpath.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xslt.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/xsltext.pxi -> build/lib.linux-aarch64-cpython-312/lxml
      copying src/lxml/includes/__init__.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/c14n.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.linux-aarch64-cpython-312/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.linux-aarch64-cpython-312/lxml/includes
      creating build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/rng
      creating build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl
      creating build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-aarch64-cpython-312/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.linux-aarch64-cpython-312/src/lxml
      aarch64-linux-android-clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -DCYTHON_CLINE_IN_TRACEBACK=0 -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -Isrc -Isrc/lxml/includes -I/data/data/com.termux/files/usr/include/python3.12 -c src/lxml/etree.c -o build/temp.linux-aarch64-cpython-312/src/lxml/etree.o -w
      src/lxml/etree.c:113221:38: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       113221 |   __pyx_v_self->_c_ctxt->sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
              |                                      ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:117709:25: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       117709 |     __pyx_v_sax->serror = __pyx_f_4lxml_5etree__receiveParserError;
              |                         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:181971:28: error: incompatible function pointer types assigning to 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') from 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') [-Wincompatible-function-pointer-types]
       181971 |   __pyx_v_xpathCtxt->error = __pyx_f_4lxml_5etree__receiveXPathError;
              |                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      src/lxml/etree.c:219245:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       219245 |   xmlRelaxNGSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/relaxng.h:156:30: note: passing argument to parameter 'serror' here
        156 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:219663:60: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       219663 |     xmlRelaxNGSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/relaxng.h:185:31: note: passing argument to parameter 'serror' here
        185 |                                           xmlStructuredErrorFunc serror, void *ctx);
            |                                                                  ^
      src/lxml/etree.c:220552:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       220552 |   xmlSchemaSetParserStructuredErrors(__pyx_v_parser_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:156:30: note: passing argument to parameter 'serror' here
        156 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:221095:59: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       221095 |     xmlSchemaSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
        185 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:221860:66: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       221860 |     xmlSchemaSetValidStructuredErrors(__pyx_v_self->_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_error_log));
              |                                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlschemas.h:185:30: note: passing argument to parameter 'serror' here
        185 |                                          xmlStructuredErrorFunc serror,
            |                                                                 ^
      src/lxml/etree.c:223037:63: error: incompatible function pointer types passing 'void (void *, xmlError *)' (aka 'void (void *, struct _xmlError *)') to parameter of type 'xmlStructuredErrorFunc' (aka 'void (*)(void *, const struct _xmlError *)') [-Wincompatible-function-pointer-types]
       223037 |     xmlSchematronSetValidStructuredErrors(__pyx_v_valid_ctxt, __pyx_f_4lxml_5etree__receiveError, ((void *)__pyx_v_self->__pyx_base._error_log));
              |                                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /data/data/com.termux/files/usr/include/libxml2/libxml/schematron.h:106:31: note: passing argument to parameter 'serror' here
        106 |                                           xmlStructuredErrorFunc serror,
            |                                                                  ^
      9 errors generated.
      Compile failed: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      creating data/data/com.termux/files/usr/tmp
      cc -I/data/data/com.termux/files/usr/include/libxml2 -I/data/data/com.termux/files/usr/include -I/usr/include/libxml2 -c /data/data/com.termux/files/usr/tmp/xmlXPathInite1cd5z36.c -o data/data/com.termux/files/usr/tmp/xmlXPathInite1cd5z36.o
      /data/data/com.termux/files/usr/tmp/xmlXPathInite1cd5z36.c:3:5: warning: 'xmlXPathInit' is deprecated [-Wdeprecated-declarations]
          3 |     xmlXPathInit();
            |     ^
      /data/data/com.termux/files/usr/include/libxml2/libxml/xpath.h:566:1: note: 'xmlXPathInit' has been explicitly marked deprecated here
        566 | XML_DEPRECATED
            | ^
      /data/data/com.termux/files/usr/include/libxml2/libxml/xmlexports.h:69:43: note: expanded from macro 'XML_DEPRECATED'
         69 |     #define XML_DEPRECATED __attribute__((deprecated))
            |                                           ^
      1 warning generated.
      cc data/data/com.termux/files/usr/tmp/xmlXPathInite1cd5z36.o -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr//data/data/com.termux/files/usr/lib -lxml2 -o a.out
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lxml
  Running setup.py clean for lxml
Failed to build lxml
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lxml)
```
