### ISSUE TITLE
[Bug]: vulkan-validation-layers don't do any validation

### ISSUE THREAD

**Issue by AnonN10** [termux/termux-packages#25416]
### Problem description

VVL doesn't do validation of any vulkan calls, even making explicitly invalid ones doesn't trigger it, the only thing that seems to make it call debug callback set up by the application is to enable verbose logging, at which point it only prints messages like "device 0 has been copied to device 0"

### What steps will reproduce the bug?

install vulkan-loader and vulkan-loader-generic to use the android driver for adreno gpu

### What is the expected behavior?

validation layers should output diagnostic messages to the debug callback

### System information

```shell
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__APK_FILE=/data/app/~~slR_62PetpD1pQ7yKohXDQ==/com.termux-skhAq_dYgBY0gWkRandPeA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__APP_VERSION_CODE=1020
TERMUX_APP__APP_VERSION_NAME=0.119.0-beta.1
TERMUX_APP__DATA_DIR=/data/user/0/com.termux
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PID=10370
TERMUX_APP__TARGET_SDK=28
TERMUX_VERSION=0.119.0-beta.1
TERMUX__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c68,c257,c512,c768
TERMUX__SE_INFO=default:targetSdkVersion=28:complete
TERMUX__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c68,c257,c512,c768
TERMUX__UID=10324
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb http://mirror.mephi.ru/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb http://mirror.mephi.ru/termux/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
Updatable packages:
chromium/x11 138.0.7204.157 aarch64 [upgradable from: 138.0.7204.100]
clvk/stable 0.0.20250714.081613 aarch64 [upgradable from: 0.0.20250703.065636]
command-not-found/stable 3.1-3 aarch64 [upgradable from: 3.1-2]
curl/stable 8.15.0 aarch64 [upgradable from: 8.14.1]
eza/stable 0.23.0 aarch64 [upgradable from: 0.22.0]
fastfetch/stable 2.48.1 aarch64 [upgradable from: 2.47.0]
gst-plugins-bad/stable 1.26.4 aarch64 [upgradable from: 1.26.3]
gst-plugins-base/stable 1.26.4 aarch64 [upgradable from: 1.26.3]
gst-plugins-good/stable 1.26.4 aarch64 [upgradable from: 1.26.3]
gstreamer/stable 1.26.4 aarch64 [upgradable from: 1.26.3]
imagemagick/stable 7.1.2.0 aarch64 [upgradable from: 7.1.1.47-1]
libcurl/stable 8.15.0 aarch64 [upgradable from: 8.14.1]
libnspr/stable 4.37 aarch64 [upgradable from: 4.36]
libnss/stable 3.114 aarch64 [upgradable from: 3.113.1]
libsqlite/stable 3.50.3 aarch64 [upgradable from: 3.50.2]
libunbound/stable 1.23.1 aarch64 [upgradable from: 1.23.0-1]
libxml2/stable 2.14.5 aarch64 [upgradable from: 2.14.4]
readline/stable 8.3.1 aarch64 [upgradable from: 8.3]
spirv-headers/stable 1.4.321.0 all [upgradable from: 1.4.313.0]
thunar/x11 4.20.4 aarch64 [upgradable from: 4.20.3]
vulkan-headers/stable 1.4.323 all [upgradable from: 1.4.322]
vulkan-loader-generic/stable 1.4.322 aarch64 [upgradable from: 1.4.321]
termux-tools version:
1.45.0
Android version:
15
Kernel build information:
Linux localhost 6.6.30-android15-8-30455426-abogkiS9310ZHS4AYF1-4k #1 SMP PREEMPT Mon Jun  9 01:59:29 UTC 2025 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S9310
Supported ABIs:
SUPPORTED_ABIS: arm64-v8a
SUPPORTED_32_BIT_ABIS: 
SUPPORTED_64_BIT_ABIS: arm64-v8a
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec-ld-preload.so
Installed termux plugins:
com.termux.api versionCode:1000
com.termux.x11 versionCode:15
```

**Comment by robertkirkman** [comment]
Is there a script, command or program you can show which can reproduce the problem and be used to check whether the problem is still present or not,

and also, you mentioned that you have Adreno GPU, but that you installed `vulkan-loader-generic`. Usually, the package `mesa-vulkan-icd-freedreno` works better for Adreno than `vulkan-loader-generic`, at least for me. What happens if you try that instead?

**Comment by AnonN10** [comment]
What happens is that I get a vulkan device that barely supports anything and is useless, as opposed to native driver

Unfortunately the program I'm using to test is sdl2 based personal project not.publicly available and one that uses quite a lot of modern vulkan features for it to be feasible for testing. I suppose one might instead use modified vkcube with explicitly added invalid vulkan code to it

**Comment by robertkirkman** [comment]
What happens if you try using `pkg install vulkan-loader-android` instead of `pkg install vulkan-loader-generic`, and what happens if you download the code of, compile and use the package in this PR, which is an experiment to try to make an alternative to `vulkan-loader-android`?

- https://github.com/termux/termux-packages/pull/22500

I would guess that if the problem is present in the `vulkan-validation-layers` package, then the problem should be reproducible using every different kind of Vulkan driver, but if some Vulkan drivers have different results, then the situation might be more complicated.

And finally, what happens if you try using **lavapipe** (software rendering, CPU, no GPU connection) to test the `mesa-vulkan-icd-swrast` package + `vulkan-validation-layers` package simultaneously?

```
pkg install mesa-vulkan-icd-swrast # will prevent Vulkan code from accessing hardware GPU
export LIBGL_ALWAYS_SOFTWARE=1 # will prevent OpenGL code from accessing hardware GPU
```

If the results after the above commands are still not the expected results, then that confirms that there is a problem with the `vulkan-validation-layers` package in Termux itself, but if the results are the expected results when the test is performed while using software rendering, then something more complicated than that might be happening.

**Comment by AnonN10** [comment]
I'm not sure it has to do with drivers because VVL is supposed to run mostly host-side, orthogonal to the driver, besides some device information querying. I'll poke around and see, based on what you suggested, it might take some time.

**Comment by AnonN10** [comment]
@robertkirkman @xMeM could you perhaps provide a build of `vulkan-wrapper-android` so I could try things out a bit faster? I'm not sure I can build it on termux from what I've tried so far, and the setup is quite alien to me (e.g. downloading dozens of packages and a massive repo just to build a single one, and what it seems to be a missing termux-exec).

**Comment by robertkirkman** [comment]
I can try in a while to do that for you, but it would probably be easier to test software rendering first using the `mesa-vulkan-icd-swrast`, just to make sure that the vulkan-validation-layers problem still happens under those conditions.

It's technically possible to build the package you just tried to on Termux, but doing that requires a lot of commands. Here are the correct commands to build it on-device as of July 24 2025:

```bash
git clone -b dev/wrapper https://github.com/xMeM/termux-packages.git termux-packages-vulkan-wrapper-android
git clone https://github.com/termux/termux-packages.git termux-packages-vulkan-wrapper-android-ondevice
cp -r termux-packages-vulkan-wrapper-android/packages/vulkan-wrapper-android/ termux-packages-vulkan-wrapper-android-ondevice/packages/
cd termux-packages-vulkan-wrapper-android-ondevice/

git apply -v << 'EOF'
--- a/packages/vulkan-wrapper-android/build.sh
+++ b/packages/vulkan-wrapper-android/build.sh
@@ -38,6 +38,10 @@ termux_step_pre_configure() {
 
 	CPPFLAGS+=" -D__USE_GNU"
 	LDFLAGS+=" -landroid-shmem"
+ 
+	if [ "$TERMUX_ON_DEVICE_BUILD" = "true" ]; then
+		CPPFLAGS+=" -D__ANDROID_API__=$(getprop ro.build.version.sdk)"
+	fi
 
 	_WRAPPER_BIN=$TERMUX_PKG_BUILDDIR/_wrapper/bin
 	mkdir -p $_WRAPPER_BIN
--- a/scripts/build/setup/termux_setup_meson.sh
+++ b/scripts/build/setup/termux_setup_meson.sh
@@ -60,6 +60,9 @@ termux_setup_meson() {
 	if [[ -n "$(command -v rustc)" && -n "${CARGO_TARGET_NAME-}" ]]; then
 		echo "rust = ['rustc', '--target', '$CARGO_TARGET_NAME']" >> $TERMUX_MESON_CROSSFILE
 	fi
+	if [ "$TERMUX_ON_DEVICE_BUILD" = "true" ]; then
+		echo "llvm-config = 'llvm-config'" >> $TERMUX_MESON_CROSSFILE
+	fi
 
 	if [ "$TERMUX_PACKAGE_LIBRARY" = "bionic" ]; then
 		echo '' >> $TERMUX_MESON_CROSSFILE
--- a/scripts/build/termux_step_copy_into_massagedir.sh
+++ b/scripts/build/termux_step_copy_into_massagedir.sh
@@ -2,6 +2,6 @@ termux_step_copy_into_massagedir() {
 	local DEST="$TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX_CLASSICAL"
 	mkdir -p "$DEST"
 	# Copy files changed during the build into massagedir in order to massage them
-	tar -C "$TERMUX_PREFIX_CLASSICAL" -N "$TERMUX_BUILD_TS_FILE" --exclude='tmp' -cf - . | \
+	tar -C "$TERMUX_PREFIX_CLASSICAL" -N "$TERMUX_BUILD_TS_FILE" --exclude='tmp' --exclude='__pycache__' -cf - . | \
 		tar -C "$DEST" -xf -
 }
EOF

scripts/setup-termux.sh
pip install mako pyyaml
./build-package.sh -I -f vulkan-wrapper-android
```

**Comment by robertkirkman** [comment]
Those patches are for compiling mesa-based packages within Termux itself, so they are for the normal `mesa` package as well as that one, and I have been working on upstreaming (to github.com/termux/termux-packages repository) as many of them as possible.

A lot more patches used to be required, but these are the last few that I haven't finished upstreaming yet.

**Comment by AnonN10** [comment]
I'm mainly concerned about setup-termux.sh script, I'm getting stuck downloading them for some reason, surely there has to be a way to get only the packages actually required for building a specific termux package? From what I understand the script is made under assumption that you're going to do an automated build of all of them on a server and the repo is not suited for targeted development of individual packages.

**Comment by robertkirkman** [comment]
> I'm getting stuck downloading them for some reason, surely there has to be a way to get only the packages actually required for building a specific termux package? 

This seems strange, could you send a log or screenshot of what you see happening?

**Comment by robertkirkman** [comment]
The packages installed by the `scripts/setup-termux.sh` script are considered to be required dependencies for building any package in the termux-packages repository on-device, because they are an approximation of the default contents of Termux's CI's Ubuntu Docker container for cross-compilation, so none of the packages there are required to be added to explicit build dependencies in the `TERMUX_PKG_BUILD_DEPENDS` variable.

**Comment by AnonN10** [comment]
> This seems strange, could you send a log or screenshot of what you see happening?

basically just network issues on my end

> The packages installed by the scripts/build-termux.sh script are considered to be required dependencies for building any package in the termux-packages repository on-device

I see, no way around it then

**Comment by AnonN10** [comment]
I tried your script, seems like it's outdated by now

```
error: while searching for:
    CPPFLAGS+=" -D__USE_GNU"
    LDFLAGS+=" -landroid-shmem"

    _WRAPPER_BIN=$TERMUX_PKG_BUILDDIR/_wrapper/bin
    mkdir -p $_WRAPPER_BIN
    if [ "$TERMUX_ON_DEVICE_BUILD" = "false" ]; then

error: patch failed: packages/vulkan-wrapper-android/build.sh:39
error: packages/vulkan-wrapper-android/build.sh: patch does not apply
Checking patch scripts/build/setup/termux_setup_meson.sh...
error: while searching for:
    echo "ld = '$LD'" >> $TERMUX_MESON_CROSSFILE
    echo "pkg-config = '$PKG_CONFIG'" >> $TERMUX_MESON_CROSSFILE
    echo "strip = '$STRIP'" >> $TERMUX_MESON_CROSSFILE

    if [ "$TERMUX_PACKAGE_LIBRARY" = "bionic" ]; then
        echo '' >> $TERMUX_MESON_CROSSFILE

error: patch failed: scripts/build/setup/termux_setup_meson.sh:57
error: scripts/build/setup/termux_setup_meson.sh: patch does not apply
Checking patch scripts/build/termux_step_copy_into_massagedir.sh...
error: while searching for:
    local DEST="$TERMUX_PKG_MASSAGEDIR/$TERMUX_PREFIX_CLASSICAL"
    mkdir -p "$DEST"
    # Copy files changed during the build into massagedir in order to massage them
    tar -C "$TERMUX_PREFIX_CLASSICAL" -N "$TERMUX_BUILD_TS_FILE" --exclude='tmp' -cf - . | \
        tar -C "$DEST" -xf -
}

error: patch failed: scripts/build/termux_step_copy_into_massagedir.sh:2
error: scripts/build/termux_step_copy_into_massagedir.sh: patch does not apply
```

**Comment by robertkirkman** [comment]
> I tried your script, seems like it's outdated by now

Thanks, that's right, the master branch has moved on since the last time I had updated that.

I've rebased it and retested the script, then I edited my message above to have a script that currently works as of today to build the `vulkan-wrapper-android` package on-device, does that help?

**Comment by robertkirkman** [comment]
>  what seems to be a missing termux-exec

I wondered what you meant about this for a while, but eventually, I thought about it and I realized that you must have seen this error at some point:

```
ERROR: On-device builds without termux-exec are not supported.
```

I believe this could happen in this situation as a result of accidentally using an outdated version of the `build-package.sh`+`scripts` folder, which are the Termux package build system code, because it seems similar to an issue that I fixed in this PR a while ago:

- https://github.com/termux/termux-packages/pull/23952

therefore, it should be possible to reliably prevent that error from happening again by making sure to use versions of `build-package.sh`+`scripts` folder that are both newer than the day that PR was merged. For example, this part of the commands above are the specific commands that prevent that error in my example:

```bash
git clone -b dev/wrapper https://github.com/xMeM/termux-packages.git termux-packages-vulkan-wrapper-android
git clone https://github.com/termux/termux-packages.git termux-packages-vulkan-wrapper-android-ondevice
cp -r termux-packages-vulkan-wrapper-android/packages/vulkan-wrapper-android/ termux-packages-vulkan-wrapper-android-ondevice/packages/
cd termux-packages-vulkan-wrapper-android-ondevice/
```

This works by downloading both the downstream branch and the master branch, and just copying the package folder `packages/vulkan-wrapper-android` from the old branch to the equivalent folder in the current repository, and building it there.

This is the way I usually build older/downstream Termux packages, in most cases.

I am sorry that I don't know how to solve your real problem yet, but I hope this explanation can solve the lesser errors you experienced while trying to troubleshoot this.

**Comment by AnonN10** [comment]
With some minor fixing (and some pain), I have built and installed the driver, layers still don't output anything, used this line to try and trigger them:
```
vkDestroyInstance(nullptr, nullptr);
```
but it's silent.

Also, some stuff doesn't work anymore, like file roller app and glmark2, I assume it's broken opengl:
```
❯ file-roller
ATTENTION: default value of option vblank_mode overridden by environment.
ZINK: USING LAZY DESCRIPTORS
../src/src/gallium/drivers/zink/zink_resource.c:804: struct zink_resource_object *resource_object_create(struct zink_screen *, const struct pipe_resource *, struct winsys_handle *, _Bool *, const uint64_t *, int): assertion "reqs.memoryTypeBits & BITFIELD_BIT(mai.memoryTypeIndex)" failed
Aborted                    file-roller
```

frankly I'm not so sure I installed the wrapper correctly, is there a specific thing I should do beyond unpacking the *.deb into the /usr/ folder? I'm not aware of how the wrapper operates exactly, whether its an icd or a loader - wrapper sounds like neither.

**Comment by robertkirkman** [comment]
Yes, that's what happens for me too, on my devices that vulkan-wrapper-android doesn't work on.

It works on some devices, but I don't have any of the devices that it works really well on.

Since you have Adreno 830, which is a new GPU that is not well-supported yet, I would suggest that software rendering is probably the only mode that can be guaranteed to work with most things on Termux on your device. However, it's unknown whether software rendering would also work around your vulkan-validation-layers problem or not.

**Comment by AnonN10** [comment]
Hmmm, the app I'm using to test won't even run with swrast driver because the device capabilities it gives aren't enough. I guess I'll have to build vkcube or something somehow.

I'm still skeptical this has anything to do with the driver, because the layers I managed to build from source (from official khronos repo) at least worked, albeit incorrectly due to how termux does the WSI, which I never figured out.

For what it's worth, I might as well build and use my own VVL if I ever do figure out how termux WSI works.

**Comment by AnonN10** [comment]
May I ask you to test it on your end if it isn't too much trouble?

**Comment by robertkirkman** [comment]
I will try soon, I'll let you know what results I find.

**Comment by AnonN10** [comment]
I've got an idea, I might try to build the debug version of the VVL package and, well, debug it by stepping through vulkan calls that should inevitably end up in VVL. Maybe I could find why nothing happens this way. Now what's left is to actually figure out how to get the debug build, probably should be as simple as applying patches manually and building with my toolchain.
