### ISSUE TITLE
Issue installing cryptography (due to openssl built with no-engine)

### ISSUE THREAD

**Issue by skittles9823** [termux/termux-packages#2847]
I'v been trying to run a local instance of my telegram bot and I've run into some issues. Previously all I've needed to do was

`pkg install clang && pkg install python-dev && pkg install postgresql-dev && pkg install libcrypt-dev`

Along with `pip install -r requirements.txt` and all would be fine. However after updating to Android Pie and. Trying to setup my local bot I ran into this;

```$ pip install cryptography
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/22/21/233e38f74188db94e8451ef6385754a98f3cad9b59bedf3a8e8b14988be4/cryptography-2.3.1.tar.gz
Requirement already satisfied: idna>=2.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from cryptography) (2.7)
Requirement already satisfied: asn1crypto>=0.21.0 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from cryptography) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from cryptography) (1.11.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from cryptography) (1.11.5)
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.7->cryptography) (2.18)
Installing collected packages: cryptography
  Running setup.py install for cryptography ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-89ifg1bb/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-h_by88vu/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-aarch64-3.6/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-aarch64-3.6/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-aarch64-3.6/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-3.6/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-aarch64-3.6/cryptography
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat
    creating build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-3.6/cryptography/x509
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/backends/openssl
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-3.6/cryptography/hazmat/bindings/openssl
    running egg_info
    writing src/cryptography.egg-info/PKG-INFO
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing requirements to src/cryptography.egg-info/requires.txt
    writing top-level names to src/cryptography.egg-info/top_level.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-aarch64-3.6/_padding.c'
    creating build/temp.linux-aarch64-3.6
    generating cffi module 'build/temp.linux-aarch64-3.6/_constant_time.c'
    generating cffi module 'build/temp.linux-aarch64-3.6/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-aarch64-3.6/build
    creating build/temp.linux-aarch64-3.6/build/temp.linux-aarch64-3.6
    aarch64-linux-android-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Oz -Oz -fPIC -I/data/data/com.termux/files/usr/include/python3.6m -c build/temp.linux-aarch64-3.6/_openssl.c -o build/temp.linux-aarch64-3.6/build/temp.linux-aarch64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-aarch64-3.6/_openssl.c:1834:14: error: unknown type name 'ENGINE_CMD_DEFN'
    static const ENGINE_CMD_DEFN osrandom_cmd_defns[] = {
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1835:6: error: use of undeclared identifier 'ENGINE_CMD_BASE'
        {CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION,
         ^
    build/temp.linux-aarch64-3.6/_openssl.c:678:50: note: expanded from macro 'CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION'
    #define CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION ENGINE_CMD_BASE
                                                     ^
    build/temp.linux-aarch64-3.6/_openssl.c:1838:6: error: use of undeclared identifier 'ENGINE_CMD_FLAG_NO_INPUT'
         ENGINE_CMD_FLAG_NO_INPUT},
         ^
    build/temp.linux-aarch64-3.6/_openssl.c:1847:10: error: use of undeclared identifier 'ENGINE_CMD_BASE'
        case CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION:
             ^
    build/temp.linux-aarch64-3.6/_openssl.c:678:50: note: expanded from macro 'CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION'
    #define CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION ENGINE_CMD_BASE
                                                     ^
    build/temp.linux-aarch64-3.6/_openssl.c:1857:23: error: use of undeclared identifier 'ENGINE_F_ENGINE_CTRL'
                ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_INVALID_ARGUMENT);
                          ^
    build/temp.linux-aarch64-3.6/_openssl.c:1857:45: error: use of undeclared identifier 'ENGINE_R_INVALID_ARGUMENT'
                ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_INVALID_ARGUMENT);
                                                ^
    build/temp.linux-aarch64-3.6/_openssl.c:1863:19: error: use of undeclared identifier 'ENGINE_F_ENGINE_CTRL'
            ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED);
                      ^
    build/temp.linux-aarch64-3.6/_openssl.c:1863:41: error: use of undeclared identifier 'ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED'
            ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED);
                                            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1947:9: warning: implicit declaration of function 'ENGINE_by_id' is invalid in C99 [-Wimplicit-function-declaration]
        e = ENGINE_by_id(Cryptography_osrandom_engine_id);
            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1947:7: warning: incompatible integer to pointer conversion assigning to 'ENGINE *' (aka 'struct engine_st *') from 'int' [-Wint-conversion]
        e = ENGINE_by_id(Cryptography_osrandom_engine_id);
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-aarch64-3.6/_openssl.c:1949:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1955:9: warning: implicit declaration of function 'ENGINE_new' is invalid in C99 [-Wimplicit-function-declaration]
        e = ENGINE_new();
            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1955:7: warning: incompatible integer to pointer conversion assigning to 'ENGINE *' (aka 'struct engine_st *') from 'int' [-Wint-conversion]
        e = ENGINE_new();
          ^ ~~~~~~~~~~~~
    build/temp.linux-aarch64-3.6/_openssl.c:1959:10: warning: implicit declaration of function 'ENGINE_set_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_set_id(e, Cryptography_osrandom_engine_id) ||
             ^
    build/temp.linux-aarch64-3.6/_openssl.c:1960:14: warning: implicit declaration of function 'ENGINE_set_name' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_name(e, Cryptography_osrandom_engine_name) ||
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1961:14: warning: implicit declaration of function 'ENGINE_set_RAND' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_RAND(e, &osrandom_rand) ||
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1962:14: warning: implicit declaration of function 'ENGINE_set_init_function' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_init_function(e, osrandom_init) ||
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1963:14: warning: implicit declaration of function 'ENGINE_set_finish_function' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_finish_function(e, osrandom_finish) ||
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1964:14: warning: implicit declaration of function 'ENGINE_set_cmd_defns' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_cmd_defns(e, osrandom_cmd_defns) ||
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1965:14: warning: implicit declaration of function 'ENGINE_set_ctrl_function' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_ctrl_function(e, osrandom_ctrl)) {
                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:1966:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1969:10: warning: implicit declaration of function 'ENGINE_add' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_add(e)) {
             ^
    build/temp.linux-aarch64-3.6/_openssl.c:1970:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-3.6/_openssl.c:1973:10: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_free(e)) {
             ^
    build/temp.linux-aarch64-3.6/_openssl.c:2660:19: warning: comparison of integers of different signs: 'int' and 'unsigned int' [-Wsign-compare]
        for (i = 0; i < _ssl_locks_count; i++) {
                    ~ ^ ~~~~~~~~~~~~~~~~
    build/temp.linux-aarch64-3.6/_openssl.c:2701:39: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
            memcpy(buf, st->password, st->length);
            ~~~~~~                    ~~~~^~~~~~
    build/temp.linux-aarch64-3.6/_openssl.c:7200:12: error: use of undeclared identifier 'ENGINE_METHOD_ALL'
      int n = (ENGINE_METHOD_ALL) <= 0;
               ^
    build/temp.linux-aarch64-3.6/_openssl.c:7201:30: error: use of undeclared identifier 'ENGINE_METHOD_ALL'
      *o = (unsigned long long)((ENGINE_METHOD_ALL) | 0);  /* check that ENGINE_METHOD_ALL is an integer */
                                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:7207:12: error: use of undeclared identifier 'ENGINE_METHOD_CIPHERS'
      int n = (ENGINE_METHOD_CIPHERS) <= 0;
               ^
    build/temp.linux-aarch64-3.6/_openssl.c:7208:30: error: use of undeclared identifier 'ENGINE_METHOD_CIPHERS'
      *o = (unsigned long long)((ENGINE_METHOD_CIPHERS) | 0);  /* check that ENGINE_METHOD_CIPHERS is an integer */
                                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:7214:12: error: use of undeclared identifier 'ENGINE_METHOD_DIGESTS'
      int n = (ENGINE_METHOD_DIGESTS) <= 0;
               ^
    build/temp.linux-aarch64-3.6/_openssl.c:7215:30: error: use of undeclared identifier 'ENGINE_METHOD_DIGESTS'
      *o = (unsigned long long)((ENGINE_METHOD_DIGESTS) | 0);  /* check that ENGINE_METHOD_DIGESTS is an integer */
                                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:7221:12: error: use of undeclared identifier 'ENGINE_METHOD_DSA'
      int n = (ENGINE_METHOD_DSA) <= 0;
               ^
    build/temp.linux-aarch64-3.6/_openssl.c:7222:30: error: use of undeclared identifier 'ENGINE_METHOD_DSA'
      *o = (unsigned long long)((ENGINE_METHOD_DSA) | 0);  /* check that ENGINE_METHOD_DSA is an integer */
                                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:7228:12: error: use of undeclared identifier 'ENGINE_METHOD_NONE'
      int n = (ENGINE_METHOD_NONE) <= 0;
               ^
    build/temp.linux-aarch64-3.6/_openssl.c:7229:30: error: use of undeclared identifier 'ENGINE_METHOD_NONE'
      *o = (unsigned long long)((ENGINE_METHOD_NONE) | 0);  /* check that ENGINE_METHOD_NONE is an integer */
                                 ^
    build/temp.linux-aarch64-3.6/_openssl.c:7235:12: error: use of undeclared identifier 'ENGINE_METHOD_RAND'
      int n = (ENGINE_METHOD_RAND) <= 0;
               ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    18 warnings and 20 errors generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-89ifg1bb/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-h_by88vu/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-89ifg1bb/cryptography/

**Comment by Grimler91** [comment]
Seems that cryptography, for now, won't work if openssl is compiled with no-engine ([which our openssl is](https://github.com/termux/termux-packages/blob/876c73c68056dbf880e21ffbbed5f6f500e89eab/packages/openssl/build.sh#L33)), see https://github.com/pyca/cryptography/issues/4412. They seem to be working on fixing this: https://github.com/pyca/cryptography/issues/3867.

**Comment by skittles9823** [comment]
@Grimler91 Ahh thanks. That explains it.

**Comment by zzxxtt** [comment]
Same problem, anyone knows how to solve the problem? 
Can the termux openssl build config remove no-engine? Or anyone has the deb of older versions of openssl?

**Comment by xeffyr** [comment]
> Or anyone has the deb of older versions of openssl?

@zzxxtt Termux uses `rolling-release` scheme for publishing package updates. So if you install `openssl` v1.0.x you will break `apt` and other things that use openssl library.

**Comment by zzxxtt** [comment]
@xeffyr Thank you. So is it possible to remove the no-engine flag in the build config of termux openssl?
Acoording to the issue pyca/cryptography#4412, it saids "the pyca maintainers are unlikely to do the work for this (work with no-engine)". However cryptography is an important dependency for lots of python package.
Can you considering remove the flag?

**Comment by skittles9823** [comment]
@xeffyr thanks :)

**Comment by xeffyr** [comment]
@vladosam For ARM:
[openssl_1.1.1-2_arm.deb.gz](https://github.com/termux/termux-packages/files/2408158/openssl_1.1.1-2_arm.deb.gz)
[openssl-dev_1.1.1-2_arm.deb.gz](https://github.com/termux/termux-packages/files/2408159/openssl-dev_1.1.1-2_arm.deb.gz)
[openssl-tool_1.1.1-2_arm.deb.gz](https://github.com/termux/termux-packages/files/2408160/openssl-tool_1.1.1-2_arm.deb.gz)

**Comment by vladosam** [comment]
Thanks @xeffyr. I can install cryptography now. But if openssl is upgraded in termux packages this will stop working??

**Comment by Grimler91** [comment]
@vladosam only if the [ABI](https://en.wikipedia.org/wiki/Application_binary_interface) of openssl changes, this is only suppose to happen on major updates. 

If something you've install locally stops working due to an update it's often enough to just reinstall/recompile the package to get it working again

**Comment by bensh4** [comment]
Not good. I just updated openssl and was installing it, and came infront of this issue. !

**Comment by Grimler91** [comment]
>  is there any way to downgrade the openssl package to get rid of this ? 

@bensh4 no, not really, openssl is such a fundamental package that if you try to downgrade it you'll break apt and many other packages and probably need to reinstall termux to get it working again

**Comment by bensh4** [comment]
@Grimler91 Wondering what happened in new update?

**Comment by bensh4** [comment]
@Grimler91 @xeffyr has given arm packages of openssl to remove no-engine . Will that make any kind of conflict if I overwrite the existing package?

**Comment by Grimler91** [comment]
No, it's the same version but with different configuration options, you can install it without problem.

**Comment by bensh4** [comment]
@Grimler91 Thanks . Btw. Could you please refer this https://github.com/termux/termux-packages/issues/429
I'm still facing this bug !

**Comment by bensh4** [comment]
@fornwall Yes. It 'd be nice. So that we can upgrade whenever latest version is available. Else we've to stick with that config file given by @xeffyr

**Comment by marteker789** [comment]
Hi guys , i am a beginner user of termux , can you help me to install (what are the commands?) opensll file for arm device ( i have the same problem installing cryptografy . thank  you so much

**Comment by vladosam** [comment]
@marteker789 go to folder where you downloaded files then:

gunzip openssl_1.1.1-2_arm.deb.gz
gunzip openssl-dev_1.1.1-2_arm.deb.gz
gunzip openssl-tool_1.1.1-2_arm.deb.gz

dpkg -i openssl_1.1.1-2_arm.deb
dpkg -i openssl-dev_1.1.1-2_arm.deb
dpkg -i openssl-tool_1.1.1-2_arm.deb

**Comment by vladosam** [comment]
Download files with browser to your phone. Usually files are in downloads folder. Then setup storage in termux with 

termux-setup-storage

You can find downloaded files in

cd ~/storage/downloads

**Comment by marteker789** [comment]
thank you so much i try and after let you know

**Comment by marteker789** [comment]
Thank you so much  , now it seems ok..

**Comment by baslow** [comment]
Does anyone know if  `no-engine` packages are available for i686?

**Comment by vladosam** [comment]
@adrianogil you need to download files for your architecture from this post https://github.com/termux/termux-packages/issues/2847#issuecomment-423752364

**Comment by bensh4** [comment]
@adrianogil download these aarch64 files and follow the video given at the end of this description.
 
[Openssl ](https://github.com/termux/termux-packages/files/2407939/openssl_1.1.1-2_aarch64.deb.gz)

[Openssl -dev](https://github.com/termux/termux-packages/files/2407940/openssl-dev_1.1.1-2_aarch64.deb.gz)

[Openssl -tool](https://github.com/termux/termux-packages/files/2407941/openssl-tool_1.1.1-2_aarch64.deb.gz)

A video tutorial here: [Video Tutorial](https://m.youtube.com/watch?v=WX2E_znRu4E)

**Comment by miaowang14** [comment]
@bensh4 do you happen to have i686 arch files too?

**Comment by Secr3ts** [comment]
Thanks @xeffyr 👌👌

**Comment by XSecr3t** [comment]
@bensh4 i try to following your videos but still not working on me
Why? 
dpkg: error processing archive openssl_1.1.1-2_arm.deb (--install):
 package architecture (arm) does not match system (aarch64)
Errors were encountered while processing:                    openssl_1.1.1-2_arm.deb

**Comment by xeffyr** [comment]
> package architecture (arm) does not match system (aarch64)

@XSecr3t Why you are installing ARM package on AArch64 ?

**Comment by XSecr3t** [comment]
Thank you for reply!!

I dont know,just following some issues,this problem make me stuck a couple month can you help? Or something ...

The first problem just about one or two modules but that problems lead me here

**Comment by xeffyr** [comment]
@XSecr3t Get aarch64 version from https://github.com/termux/termux-packages/issues/2847#issuecomment-423752364

**Comment by XSecr3t** [comment]
@xeffyr already download but how to extract? Cause i use gzip/unzip its not working for me.

Is anything wrong with this step?

**Comment by XSecr3t** [comment]
@xeffyr can you tell me more specific?

**Comment by xeffyr** [comment]
@XSecr3t 

```
wget https://github.com/termux/termux-packages/files/2407939/openssl_1.1.1-2_aarch64.deb.gz
wget https://github.com/termux/termux-packages/files/2407940/openssl-dev_1.1.1-2_aarch64.deb.gz
gunzip openssl_1.1.1-2_aarch64.deb.gz
gunzip openssl-dev_1.1.1-2_aarch64.deb.gz
dpkg -i openssl_1.1.1-2_aarch64.deb openssl-dev_1.1.1-2_aarch64.deb
```

**Comment by XSecr3t** [comment]
This error show up 

@xeffyr 

them.
N: Skipping acquire of configured file 'main/binary-openssl-dev/Packages' as repository 'https://termux.net stable InRelease' doesn't support architecture 'openssl-dev'
N: Skipping acquire of configured file 'stable/binary-openssl-dev/Packages' as repository 'https://grimler.se root InRelease' doesn't support architecture 'openssl-dev' 

Sucks for me

**Comment by xeffyr** [comment]
@XSecr3t What you did to get that ?

**Comment by XSecr3t** [comment]
@xeffyr  I dont know,before i get with following your links, i try to install with command "pkg install openssl-dev ( in my memory ) last day

**Comment by XSecr3t** [comment]
I try to uninstall but the package not uninstalled

**Comment by xeffyr** [comment]
@XSecr3t What I can see from your error is that you messed up with sources.list file. Only you here have this error.

**Comment by XSecr3t** [comment]
@xeffyr i think my last check any file seems like openssl-dev into some folder names Archithecture,what kind directory place is?

**Comment by XSecr3t** [comment]
If i find that directory maybe i can deleted that package manually

**Comment by xeffyr** [comment]
> i think my last check any file seems like openssl-dev into some folder names Archithecture

No one of packages contain or create directory 'Architecture'. You either installed something different or just were not able to follow instructions...

**Comment by twoAcestwo8s** [comment]
New to termux, I just came across this issue, however I am running on an x86_64 vm. Are there pacakages built for x86_64?

**Comment by Secr3ts** [comment]
Are you running on Aarch or arm?

**Comment by twoAcestwo8s** [comment]
To be clear I'm running an x86 image from http://www.android-x86.org.

**Comment by twoAcestwo8s** [comment]
I would but I am trying to set up some automation via VMs. I have one phone but it's easier to clone a VM than buy a phone.

**Comment by Secr3ts** [comment]
Oh yes I understand you.. I'll try to find another image who would be compatible with these OpenSSL pkg

**Comment by Secr3ts** [comment]
There u go : LineageOs.org

**Comment by twoAcestwo8s** [comment]
Awesome thank you, I will give it a shot!

**Comment by Secr3ts** [comment]
Hope it'll work ;)

**Comment by xeffyr** [comment]
> Should we remove `no-engine` from the official openssl package?

@fornwall Since removing `no-engine` doesn't harm anything, I guess it will be better to do this. PR available: https://github.com/termux/termux-packages/pull/3051

**Comment by XSecr3t** [comment]
@xeffyr

All is done but why this issues never solved in my life
Otherwise i already installed openssl that you reference for me, but stil didn't working for me

While i run pip install cryptography

This similiar various error show up
Maybe you can help me

> root@Mr.XSecr3t:~#pip install cryptography
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/d2/5f/6ed3135eb1e775187f7ecd4e7713f1415516725365e51f9786143f36e024/cryptography-2.4.1.tar.gz
  Installing build dependencies ... done
Requirement already satisfied: idna>=2.1 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (2.7)
Requirement already satisfied: asn1crypto>=0.21.0 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (1.10.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (1.7.0)
Requirement already satisfied: enum34 in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (1.1.6)
Requirement already satisfied: ipaddress in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cryptography) (1.0.22)
Requirement already satisfied: pycparser in /data/data/com.termux/files/usr/lib/python2.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography) (2.14)
Installing collected packages: cryptography
  Running setup.py install for cryptography ... error
    Complete output from command /data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-5p2bXL/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-0YvwcG/install-record.txt --single-version-externally-managed --compile:
    WARNING: linker: /data/data/com.termux/files/usr/tmp/pip-build-env-u2VqMQ/lib/python2.7/site-packages/_cffi_backend.so: unused DT entry: type 0x6ffffef5 arg 0x890
running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-2.7
    creating build/lib.linux-aarch64-2.7/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-aarch64-2.7/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-aarch64-2.7/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-2.7/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-aarch64-2.7/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-aarch64-2.7/cryptography
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat
    copying src/cryptography/hazmat/_oid.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat
    creating build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/ocsp.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-2.7/cryptography/x509
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/backends
copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/mac.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/serialization.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/backends/openssl
at/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/backends/openssl
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/bindings/openssl
    creating build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-2.7/cryptography/hazmat/primitives/asymmetric
running egg_info
    writing requirements to src/cryptography.egg-info/requires.txt
    writing src/cryptography.egg-info/PKG-INFO
    writing top-level names to src/cryptography.egg-info/top_level.txt
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-aarch64-2.7/_padding.c'
    creating build/temp.linux-aarch64-2.7
    generating cffi module 'build/temp.linux-aarch64-2.7/_constant_time.c'
    generating cffi module 'build/temp.linux-aarch64-2.7/_openssl.c'
    building '_openssl' extension
    creating build/temp.linux-aarch64-2.7/build
    creating build/temp.linux-aarch64-2.7/build/temp.linux-aarch64-2.7
    aarch64-linux-android-clang -fno-strict-aliasing -OPT:Olimit=0 -Oz -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/data/data/com.termux/files/usr/include/python2.7 -c build/temp.linux-aarch64-2.7/_openssl.c -o build/temp.linux-aarch64-2.7/build/temp.linux-aarch64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.linux-aarch64-2.7/_openssl.c:1943:14: error: unknown type name 'ENGINE_CMD_DEFN'
    static const ENGINE_CMD_DEFN osrandom_cmd_defns[] = {
: error: use of undeclared identifier 'ENGINE_CMD_BASE'
        {CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION,
         ^
    build/temp.linux-aarch64-2.7/_openssl.c:680:50: note: expanded from macro 'CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION'
    #define CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION ENGINE_CMD_BASE
                                                     ^
    build/temp.linux-aarch64-2.7/_openssl.c:1947:6: error: use of undeclared identifier 'ENGINE_CMD_FLAG_NO_INPUT'
         ENGINE_CMD_FLAG_NO_INPUT},
         ^
    build/temp.linux-aarch64-2.7/_openssl.c:1956:10: error: use of undeclared identifier 'ENGINE_CMD_BASE'
        case CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION:
             ^
    build/temp.linux-aarch64-2.7/_openssl.c:680:50: note: expanded from macro 'CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION'
    #define CRYPTOGRAPHY_OSRANDOM_GET_IMPLEMENTATION ENGINE_CMD_BASE
                                                     ^
    build/temp.linux-aarch64-2.7/_openssl.c:1966:23: error: use of undeclared identifier 'ENGINE_F_ENGINE_CTRL'
                ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_INVALID_ARGUMENT);
                          ^
    build/temp.linux-aarch64-2.7/_openssl.c:1966:45: error: use of undeclared identifier 'ENGINE_R_INVALID_ARGUMENT'
                ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_INVALID_ARGUMENT);
                                                ^
    build/temp.linux-aarch64-2.7/_openssl.c:1972:19: error: use of undeclared identifier 'ENGINE_F_ENGINE_CTRL'
            ENGINEerr(ENGINE_F_ENGINE_CTRL, ENGINE_R_CTRL_COMMAND_NOT_IMPLEMENTED);
                      ^
    build/temp.linux-aarch64-2.7/_open
: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2056:7: warning: incompatible integer to pointer conversion assigning to 'ENGINE *' (aka 'struct engine_st *') from 'int' [-Wint-conversion]
        e = ENGINE_by_id(Cryptography_osrandom_engine_id);
          ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    build/temp.linux-aarch64-2.7/_openssl.c:2058:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-2.7/_openssl.c:2058:9: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2064:9: warning: implicit declaration of function 'ENGINE_new' is invalid in C99 [-Wimplicit-function-declaration]
        e = ENGINE_new();
            ^
    build/temp.linux-aarch64-2.7/_openssl.c:2064:9: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2064:7: warning: incompatible integer to pointer conversion assigning to 'ENGINE *' (aka 'struct engine_st *') from 'int' [-Wint-conversion]
        e = ENGINE_new();
          ^ ~~~~~~~~~~~~
    build/temp.linux-aarch64-2.7/_openssl.c:2068:10: warning: implicit declaration of function 'ENGINE_set_id' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_set_id(e, Cryptography_osrandom_engine_id) ||
             ^
    build/temp.linux-aarch64-2.7/_openssl.c:2068:10: warning: this function declaration is not a prototype [-Wstrict-prototypes]
: warning: implicit declaration of function 'ENGINE_set_name' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_name(e, Cryptography_osrandom_engine_name) ||
                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:2069:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2070:14: warning: implicit declaration of function 'ENGINE_set_RAND' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_RAND(e, &osrandom_rand) ||
                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:2070:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2071:14: warning: implicit declaration of function 'ENGINE_set_init_function' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_init_function(e, osrandom_init) ||
                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:2071:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2072:14: warning: implicit declaration of function 'ENGINE_set_finish_function' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_finish_function(e, osrandom_finish) ||
                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:2072:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2073:14: warning: implicit declaration of function 'ENGINE_set_cmd_defns' is invalid in C99 [-Wimplicit-function-declaration]
                !ENGINE_set_cmd_defns(e, osrandom_cmd_defns) ||
                 ^
: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2075:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-2.7/_openssl.c:2078:10: warning: implicit declaration of function 'ENGINE_add' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_add(e)) {
             ^
    build/temp.linux-aarch64-2.7/_openssl.c:2078:10: warning: this function declaration is not a prototype [-Wstrict-prototypes]
    build/temp.linux-aarch64-2.7/_openssl.c:2079:9: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
            ENGINE_free(e);
            ^
    build/temp.linux-aarch64-2.7/_openssl.c:2082:10: warning: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Wimplicit-function-declaration]
        if (!ENGINE_free(e)) {
             ^
    build/temp.linux-aarch64-2.7/_openssl.c:2866:39: warning: implicit conversion changes signedness: 'int' to 'unsigned long' [-Wsign-conversion]
            memcpy(buf, st->password, st->length);
            ~~~~~~                    ~~~~^~~~~~
    build/temp.linux-aarch64-2.7/_openssl.c:7529:12: error: use of undeclared identifier 'ENGINE_METHOD_ALL'
      int n = (ENGINE_METHOD_ALL) <= 0;
               ^
    build/temp.linux-aarch64-2.7/_openssl.c:7530:30: error: use of undeclared identifier 'ENGINE_METHOD_ALL'
      *o = (unsigned long long)((ENGINE_METHOD_ALL) | 0);  /* check that ENGINE_METHOD_ALL is an integer *
int n = (ENGINE_METHOD_CIPHERS) <= 0;
               ^
    build/temp.linux-aarch64-2.7/_openssl.c:7537:30: error: use of undeclared identifier 'ENGINE_METHOD_CIPHERS'
      *o = (unsigned long long)((ENGINE_METHOD_CIPHERS) | 0);  /* check that ENGINE_METHOD_CIPHERS is an integer */
                                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:7543:12: error: use of undeclared identifier 'ENGINE_METHOD_DIGESTS'
      int n = (ENGINE_METHOD_DIGESTS) <= 0;
               ^
    build/temp.linux-aarch64-2.7/_openssl.c:7544:30: error: use of undeclared identifier 'ENGINE_METHOD_DIGESTS'
      *o = (unsigned long long)((ENGINE_METHOD_DIGESTS) | 0);  /* check that ENGINE_METHOD_DIGESTS is an integer */
                                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:7550:12: error: use of undeclared identifier 'ENGINE_METHOD_DSA'
      int n = (ENGINE_METHOD_DSA) <= 0;
               ^
    build/temp.linux-aarch64-2.7/_openssl.c:7551:30: error: use of undeclared identifier 'ENGINE_METHOD_DSA'
      *o = (unsigned long long)((ENGINE_METHOD_DSA) | 0);  /* check that ENGINE_METHOD_DSA is an integer */
                                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:7557:12: error: use of undeclared identifier 'ENGINE_METHOD_NONE'
      int n = (ENGINE_METHOD_NONE) <= 0;
build/temp.linux-aarch64-2.7/_openssl.c:7558:30: error: use of undeclared identifier 'ENGINE_METHOD_NONE'
      *o = (unsigned long long)((ENGINE_METHOD_NONE) | 0);  /* check that ENGINE_METHOD_NONE is an integer */
                                 ^
    build/temp.linux-aarch64-2.7/_openssl.c:7564:12: error: use of undeclared identifier 'ENGINE_METHOD_RAND'
      int n = (ENGINE_METHOD_RAND) <= 0;
               ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    28 warnings and 20 errors generated.
    error: command 'aarch64-linux-android-clang' failed with exit status 1

    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-5p2bXL/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-0YvwcG/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-5p2bXL/cryptography/

I reallt confuse about this issues

**Comment by xeffyr** [comment]
@XSecr3t **Wait for https://github.com/termux/termux-packages/pull/3051.**

**Comment by Secr3ts** [comment]
@xeffyr can you show we were you learned this??

**Comment by Secr3ts** [comment]
@xsecret cause "- I" is -i

**Comment by twoAcestwo8s** [comment]
@Secr3ts I installed LineageOS and tried to install Paramkio again, still no luck, same error.

**Comment by Secr3ts** [comment]
I'm sorry.. May ask @xeffyr

**Comment by fornwall** [comment]
The updated package (openssl 1.1.1-3) that is built with engine support has now been pushed to the package repository, so you can now install it with `pkg up`!
