### ISSUE TITLE
SSH client variables are not set

### ISSUE THREAD

**Issue by mklein994** [termux/termux-packages#290]
When I connect to my phone over ssh, the variables `SSH_CONNECTION`, `SSH_CLIENT`, and `SSH_TTY` are not set. Is there any way this can be fixed?

**Comment by fornwall** [comment]
Can confirm this, will look into it.

**Comment by fornwall** [comment]
Thanks - this should now work in the latest 7.2p2-5 version of the openssh package. Update to it with apt update && apt upgrade and make sure to kill any old sshd server process with killall -9 sshd before starting sshd again after updating.

Let me know if there are any remaining problem!

**Comment by kirk86** [comment]
@fornwall sorry to bother with this old issue but I'm kind of having a similar situation. I tried to look online but couldn't find the answer. I'm trying to use my phone to ssh to my linux box using ssh agent forwarding, but every time I execute the command `ssh uesr@host -Y` I'm connected to my linux box, everything's fine so far but when I execute an application like `xeyes` I get the message "cant open display", any idea on that? Thanks!

**Comment by Grimler91** [comment]
@kirk86 Termux is a terminal emulator. We don't have a X server running so you can't start GUI programs.

**Comment by xeffyr** [comment]
> We don't have a X server running so you can't start GUI programs.

OpenSSH x11 forwarding uses X server on host. On Termux side it is needed only:

* To enable x11 forwarding in sshd_config.
* Install `xorg-xauth` from x11-packages repo.

Package `xeyes` is not available.
And as @Grimler91 wrote, Termux is a terminal emulator primarily.

**Comment by kirk86** [comment]
thanks folks @Grimler91 && @xeffyr, I'm trying to create sshd_config in `/system/etc/ssh` but I don't have sudo access, does anyone know what's the package for sudo, I've tried tsu and the alternative sudo script but when I execute tsudo still can't create the directory path, whereas when I use the sudo script it says no su binaries found although su pkg is installed.

**Comment by xeffyr** [comment]
> I'm trying to create sshd_config in /system/etc/ssh

Termux's OpenSSH doesn't look at /system/etc/ssh.
