### ISSUE TITLE
lldb failed to launch process

### ISSUE THREAD

**Issue by librehat** [termux/termux-packages#4282]
Latest packages on Android 9 (Samsung Galaxy Tab S5e). lldb-8.0, I was trying to debug a very simple C++ application that I just compiled on-device (using clang++-8.0). However, `lldb` is not able to launch the process

```
(lldb) run
error: process launch failed: 'A' packet returned an error: 8
```

Meanwhile, I tried to use `gdb` and it works perfectly fine. I read it somewhere else on the Internet and on some systems it had something to do with tightened pstack scope thingy? Not sure if that's the case with Android.

**Comment by buttaface** [comment]
I tried it on another Samsung tablet running Android 9, got the same error. Not able to reproduce on a non-Samsung phone running Android 8, so it depends on the device.

**Comment by xeffyr** [comment]
On Lineage OS with forced SELinux to permissive `lldb` works.

**Comment by librehat** [comment]
@buttaface I wonder if it's the "security" feature from the Samsung official ROM. 
@xeffyr Are you suggesting SELinux has something to do here?

**Comment by xeffyr** [comment]
> Are you suggesting SELinux has something to do here?

Probably. I don't know exactly since can't use SELinux in enforcing mode (will crash whole system).
Regarding ptrace scope, my kernel doesn't have sysctl entry `kernel.yama.ptrace_scope` at all. That may be another cause why lldb is working on my device.

**Comment by xeffyr** [comment]
Just tried `lldb` on AVD with Android 9, got same error:
```
error: process launch failed: 'A' packet returned an error: 8
```
It happens regardless of SELinux status, so problem lies somewhere else.

**Comment by xeffyr** [comment]
Should be fixed by https://github.com/termux/termux-packages/commit/a51d424c9ccf3d0b63f4cf0be337de5b9b8939fc.

**Comment by buttaface** [comment]
Yep, confirmed on my Pie phone.

**Comment by librehat** [comment]
Can confirm this is fixed on my Galaxy Tab S5e

**Comment by AbdullahBinJahed** [comment]
> Should be fixed by [a51d424](https://github.com/termux/termux-packages/commit/a51d424c9ccf3d0b63f4cf0be337de5b9b8939fc).

why do I still get the error ?
![Screenshot_2021-09-10-11-58-28-070_com termux](https://user-images.githubusercontent.com/39275638/132806963-4d0bd9bc-d228-414b-a444-b750c7c3c101.jpg)

**Comment by buttaface** [comment]
It's not the same error: you don't get the same `packet returned` message.

If it's always reproducible, open a new issue with the relevant info.
