### ISSUE TITLE
shmget

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#502]
Hello,

Some softwares need the shmget function which does not exist on Android.
This might be used as a workaround: https://github.com/pelya/android-shmem

**Comment by fornwall** [comment]
Do you have an example of a package needing shmget, that I can test with?

**Comment by Rudloff** [comment]
I remember opening this issue because some app was complaining about it but I don't remember which one, sorry...

**Comment by vishalbiswas** [comment]
Time to close this.
libandroid-shmem is available in the repos.

**Comment by sdrausty** [comment]
>Do you have an example of a package needing shmget, that I can test with?

```
Unpacking libandroid-shmem (0.2) ...
Setting up libandroid-shmem (0.2) ...
[02:53 downloads ]$ startarch c LD_PRELOAD=libandroid-shmem.so sudo
ERROR: ld.so: object 'libandroid-shmem.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor
sudo: fatal error, unable to load plugins
```
1) https://github.com/sdrausty/termux-archlinux/issues/4
1) https://github.com/sdrausty/TermuxArch/issues/38
3) https://github.com/sdrausty/TermuxArch/issues/55
3) https://github.com/sdrausty/TermuxArch/issues/59#issuecomment-381380567
4) https://github.com/sdrausty/TermuxArch/issues/68

**Comment by xeffyr** [comment]
@sdrausty try to rebuild libandroid-shmem in TermuxArch then put it into /usr/lib. At least this should fix this: `from LD_PRELOAD cannot be preloaded (cannot open shared object file)`.

**Comment by sdrausty** [comment]
```
[12:43 libandroid-shmem ]$ make
cc -fpic -shared -std=c11 -Wall -Wextra -Wl,--version-script=exports.txt  shmem.c -llog -o libandroid-shmem.so
shmem.c:1:10: fatal error: android/log.h: No such file or directory
 #include <android/log.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:4: libandroid-shmem.so] Error 1
[12:44 libandroid-shmem ]$ export
declare -x ANDROID_HOME="/home/e/lib/android-sdk"
declare -x ANT_HOME="/usr/share/apache-ant"
declare -x HOME="/home/e"
declare -x JAVA_HOME="/usr/lib/jvm/java-8-openjdk"
```

```
[12:44 libandroid-shmem ]$ e
[12:45 ~ ]$ cd libandroid-shmem/
[12:45 libandroid-shmem ]$ make
make: 'libandroid-shmem.so' is up to date.
[12:45 libandroid-shmem ]$ make clean
rm -f libandroid-shmem.so
[12:45 libandroid-shmem ]$ make install
cc -fpic -shared -std=c11 -Wall -Wextra -Wl,--version-script=exports.txt  shmem.c -o libandroid-shmem.so
install -D libandroid-shmem.so /data/data/com.termux/files/usr/lib/libandroid-shmem.so
install -D shm.h /data/data/com.termux/files/usr/include/sys/shm.h
```

Builds in Termux, not in TermuxArch; why?

**Comment by Grimler91** [comment]
> Builds in Termux, not in TermuxArch; why?

Because the Makefile doesn't support termuxarch.
@vishalbiswas forked it and made some changes so that it will work in arch as well, see https://github.com/vishalbiswas/libandroid-shmem-gnu.

**Comment by Grimler91** [comment]
Which error did you get from copying liblog.so?

**Comment by sdrausty** [comment]
Before `$ cp /system/lib64/liblog.so ~/arch/lib/`:
```
[15:21 aq ]$ LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-shmem.so ls
ls: error while loading shared libraries: liblog.so: cannot open shared object file: No such file or directory
```
After `$ cp /system/lib64/liblog.so ~/archi/lib/`:
```
[15:23 aq ]$ LD_PRELOAD=/data/data/com.termux/files/usr/lib/libandroid-shmem.so ls
ls: error while loading shared libraries: /usr/lib/libc.so: invalid ELF header
```
After copying libc.so and more, similar errors persist.

**Comment by Hax4us** [comment]
It is natural bcz you are using `liblog.so` from android in your Archlinux so I don't think it is possible ....

**Comment by sdrausty** [comment]
```
[00:45 ~ ]$ startarch+archi c pc a enlightenment16 xterm firefox git
```
```
[00:54 ~ ]$ startarch+archi s user gcl https://github.com/vishalbiswas/libandroid-shmem-gnu 
```
```
[00:55 ~ ]$ !cd
cd libandroid-shmem-gnu/
[00:55 libandroid-shmem-gnu ]$ make clean;make gnulinux
rm -f libandroid-shmem.so
cc -fpic -shared -std=c11 -Wall -Wextra -Wl,--version-script=exports.txt -D_GNU_SOURCE -pthread  shmem.c -o libandroid-shmem.so
[00:56 libandroid-shmem-gnu ]$ cp libandroid-shmem.so /lib/                        
[00:56 libandroid-shmem-gnu ]$ LD_PRELOAD=libandroid-shmem.so whoami               
user
[00:58 libandroid-shmem-gnu ]$ LD_PRELOAD=libandroid-shmem.so sudo
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor
sudo: fatal error, unable to load plugins
[00:58 libandroid-shmem-gnu ]$ . exd
[01:07 ~ ]$ LD_PRELOAD=libandroid-shmem.so starte16 & LD_PRELOAD=libandroid-shmem.so firefox & LD_PRELOAD=libandroid-shmem.so xterm &
[1] 28753
[2] 28754
[3] 28755
[01:07 ~ ]$ j
[1]   Running                 LD_PRELOAD=libandroid-shmem.so starte16 &
[2]-  Running                 LD_PRELOAD=libandroid-shmem.so firefox &
[3]+  Running                 LD_PRELOAD=libandroid-shmem.so xterm &
[01:07 ~ ]$ Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to lock new back buffer. (t=66.231) [GFX1-]: Failed to lock new back buffer.
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to lock new back buffer. (t=66.231) |[1][GFX1-]: Failed to lock new back buffer. (t=66.2447) [GFX1-]: Failed to lock new back buffer.
[01:07 ~ ]$ j
[1]   Running                 LD_PRELOAD=libandroid-shmem.so starte16 &
[2]-  Running                 LD_PRELOAD=libandroid-shmem.so firefox &
[3]+  Running                 LD_PRELOAD=libandroid-shmem.so xterm &
Crash Annotation GraphicsCriticalError: |[0][GFX1-]: Failed to lock new back buffer. (t=66.231) |[571][GFX1-]: Failed to lock new back buffer. (t=182.627) |[572][GFX1-]: Failed to lock new back buffer. (t=182.633) |[573][GFX1-]: Failed to lock new back buffer. (t=182.635) |[574][GFX1-]: Failed to lock new back buffer. (t=182.954) |[560][GFX1-]: Failed to lock new back buffer. (t=180.873) |[561][GFX1-]: Failed to lock new back buffer. (t=180.877) |[562][GFX1-]: Failed to lock new back buffer. (t=180.878) |[563][GFX1-]: Failed to lock new back buffer. (t=180.879) |[564][GFX1-]: Failed to lock new back buffer. (t=180.884) |[565][GFX1-]: Failed to lock new back buffer. (t=180.887) |[566][GFX1-]: Failed to lock new back buffer. (t=180.888) |[567][GFX1-]: Failed to lock new back buffer. (t=180.889) |[568][GFX1-]: Failed to lock new back buffer. (t=182.534) |[569][GFX1-]: Failed to lock new back buffer. (t=182.541) |[570][GFX1-]: Failed to lock new back buffer. (t=182.544) [GFX1-]: Failed to lock new back buffer.
```
The last message repeats forever.  After testing in Xserver XSDL: not much difference with shmems loaded.

```
[01:31 ~ ]$ cat libq                                                                              
find /proc/ -name maps -exec cat {} \; 2>/dev/null |grep shmem                                    
[01:33 ~ ]$ sh libq
```
Shows tons of shmems loaded.

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish.
