### ISSUE TITLE
Visual issues with Curses-based programs

### ISSUE THREAD

**Issue by hastebrot** [termux/termux-packages#86]
I get some visual issues with `ranger` and `htop` (both AFAIR based on a curses library).

In `ranger` some filesystem entries are (visually) removed, when I move the cursor up and down (using J and K on the keyboard). In `htop` after a while the upper area with CPU usage is overwritten by the list with running tasks.

Could also be a problem with the terminal emulator from `termux/termux-app`.

**Comment by fornwall** [comment]
Thanks a lot, didn't notice the htop issue! This was indeed a bug in the terminal emulation and has now been fixed in https://github.com/termux/termux-app/issues/28, which will be released in an update of the Termux app (version 0.22) in a day or two.

For the ranger issue I didn't manage to reproduce it yet! Could you provide steps to reproduce the issue, and perhaps a screenshot indicating exactly where the entries are removed? It could be the same bug as the above if list scrolling is involved, but I would like to reproduce the issue to be sure!

**Comment by hastebrot** [comment]
I've ˋgit cloneˋd a repository and went into this directory [1]. Some entries in ˋrangerˋ disappear when I move a single entry up (with ˋKˋ), after I moved some entries down (with ˋJˋ). It is always the same entry and can be repeated here. When I disable the file preview (with ˋ:set preview_files falseˋ) the issue goes away; however in another directory the issue still occured.

[1] https://github.com/TestFX/TestFX/tree/master/subprojects/testfx-core/src/main/java/org/testfx/api

**Comment by hastebrot** [comment]
![screenshot_2015-12-12-00-48-25](https://cloud.githubusercontent.com/assets/496255/11758559/9455ebae-a06c-11e5-919c-076355e0bf7e.png)

(made this screenshot without updating termux)

Thanks for all the great work!

**Comment by fornwall** [comment]
Thanks a lot for the help reproducing the problem!

It was indeed caused by the same terminal emulation bug that affected htop, which is fixed in https://github.com/termux/termux-app/issues/28 and will be released in Termux version 0.22, to be available in Google Play in a couple of hours!

**Comment by hastebrot** [comment]
Wow, amazing! :smile_cat:
