### ISSUE TITLE
Main repo package.termux.org is being transfered to another server

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#9286]
### Problem description

The main repository cannot be accessed currently. To be able to update packages you might need to first switch to another mirror using the `termux-change-repo` tool:

1. Select one or more repositories for which you want to change mirror by tapping "space" and navigating over list by up/down arrow keys. Tap enter to confirm the choice.

![change-repo1](https://user-images.githubusercontent.com/18900601/155493129-513cbc55-cbe7-4452-86bb-c45af9544722.png)

2. Pick a mirror, it is recommended to begin with mirror hosted by Grimler. Same as previously, navigate over list by arrow keys, pick mirror by space key and confirm choice by pressing "enter".

![change-repo2](https://user-images.githubusercontent.com/18900601/155493177-4557157a-58af-4b83-bbee-dfd47187cd2c.png)

### What steps will reproduce the bug?

Trying to use pkg/apt while subscribed to the main repo

### What is the expected behavior?

pkg/apt should successfully access the repo

### System information

Happens for all devices that are subscribed to the main repo.

**Comment by macerg** [comment]
I've tried ALL of the repositories, none of them work for me.

[*] Grimler's (NL) mirrors selected
    Changing main repository                               [*] Running apt update
Ign:1 https://packages.termux.org/apt/termux-games games InRelease
Ign:2 https://packages.termux.org/apt/termux-root root InRelease
Ign:3 https://packages.termux.org/apt/termux-science science InRelease
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Hit:5 https://its-pointless.github.io/files/24 termux InRelease
Ign:1 https://packages.termux.org/apt/termux-games games InRelease
Ign:2 https://packages.termux.org/apt/termux-root root InRelease
Ign:3 https://packages.termux.org/apt/termux-science science InRelease
Get:6 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Get:7 https://grimler.se/termux-packages-24 stable/main all Packages [23.8 kB]                                        Ign:1 https://packages.termux.org/apt/termux-games games InRelease                                                    Get:8 https://grimler.se/termux-packages-24 stable/main aarch64 Packages [364 kB]                                     Ign:2 https://packages.termux.org/apt/termux-root root InRelease
Ign:3 https://packages.termux.org/apt/termux-science science InRelease
Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
Err:1 https://packages.termux.org/apt/termux-games games InRelease
  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
Err:2 https://packages.termux.org/apt/termux-root root InRelease
  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
Err:3 https://packages.termux.org/apt/termux-science science InRelease
  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
Err:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
Fetched 405 kB in 8s (48.9 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Failed to fetch https://packages.termux.org/apt/termux-games/dists/games/InRelease  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
W: Failed to fetch https://packages.termux.org/apt/termux-root/dists/root/InRelease  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
W: Failed to fetch https://packages.termux.org/apt/termux-science/dists/science/InRelease  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
W: Failed to fetch https://packages.termux.org/apt/termux-x11/dists/x11/InRelease  Something wicked happened resolving 'packages.termux.org:https' (7 - No address associated with hostname)
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by 2096779623** [comment]
> 

You need to replace all repos in $PREFIX/etc/apt/sources.list.d.

**Comment by 2096779623** [comment]
> 我已经试用了所有的存储库，它们都不适合我。
> 
> [ _] Grimler's (NL) mirrors selected 更改主存储库 [_ ] 运行 apt update Ign:1 https://packages.termux.org/apt/termux-games games InRelease Ign:2 [https://packages.termux.org/ apt /termux-root](https://packages.termux.org/apt/termux-root) root InRelease Ign:3 https://packages.termux.org/apt/termux-science science InRelease Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease Hit:5 https://its-pointless.github.io/files/24 termux InRelease Ign:1 https://packages.termux.org/apt/termux-games游戏 InRelease Ign:2 [https://packages.termux.org/ apt/termux-root](https://packages.termux.org/apt/termux-root)根 InRelease Ign:3 https://packages.termux.org/apt/termux-science科学 InRelease Get:6 https://grimler.se/termux-packages-24稳定 InRelease [16.8 kB] Ign:4 [https://packages .termux.org/apt/termux-x11](https://packages.termux.org/apt/termux-x11) x11 InRelease Get:7 https://grimler.se/termux-packages-24 stable/main all Packages [23.8 kB] Ign:1 [https://packages.termux.org/ apt/termux-games](https://packages.termux.org/apt/termux-games)游戏 InRelease Get:8 https://grimler.se/termux-packages-24 stable/main aarch64 包 [364 kB] Ign:2 https://packages.termux.org/apt/termux-root根 InRelease Ign:3 https://packages.termux.org/apt/termux-science science InRelease Ign:4[https://packages.termux.org/ apt/termux-x11](https://packages.termux.org/apt/termux-x11) x11 InRelease Err:1 https://packages.termux.org/apt/termux-games games InRelease 解决“packages.termux.org:https”时发生了一些邪恶的错误事件（7 - 没有与主机名关联的地址） ：2 https://packages.termux.org/apt/termux-root根 InRelease “packages.termux.org:https” （7 - 没有与与主机名关联的地址）名称关联的地址） 错误 ：3 https: // [packages。](https://packages.termux.org/apt/termux-science)关联的地址） Err:4 https://packages.termux.org/apt/termux-x11 x11 InRelease 解决“packages.termux”时发生了一些事情。org:https' (7 - 没有与主机名关联读取地址) 在 8 秒内获取 405 kB (48.9 kB/s) 包列表...完成[](https://packages.termux.org/apt/termux-x11) 构建关系树...完成 状态读取信息依赖...完成 1个包可以。运行'apt list --upgradable'来查看它 。W：无法获取[https://packages.termux.org/apt/ termux-games/dists/games/InRelease](https://packages.termux.org/apt/termux-games/dists/games/InRelease) 解决“packages.termux.org:https”时发生了一些糟糕的事情（7 - 没有主机名关联的地址） W：无法获取[https://packages.termux.org /apt/termux-root/dists/root/InRelease](https://packages.termux.org/apt/termux-root/dists/root/InRelease) 解决“packages.termux.org:https”（7 - 没有与主机名关联的地址） W：无法获取[https://packages.termux.org/apt/termux -science/dists/science/InRelease](https://packages.termux.org/apt/termux-science/dists/science/InRelease) 解决“packages.termux.org:https”（7 - 没有与主机名关联的地址） W：无法获取[https://packages.termux.org/apt/termux-x11/dists /x11/InRelease](https://packages.termux.org/apt/termux-x11/dists/x11/InRelease) 解决“packages.termux.org:https”（7 - 没有与主机名关联的地址） W：索引文件已被删除。它们已被删除，或者使用旧的。

You need to replace all repos in $PREFIX/etc/apt/sources.list.d.

**Comment by Grimler91** [comment]
> Ign:1 https://packages.termux.org/apt/termux-games games InRelease
> Ign:2 https://packages.termux.org/apt/termux-root root InRelease
> Ign:3 https://packages.termux.org/apt/termux-science science InRelease
> Ign:4 https://packages.termux.org/apt/termux-x11 x11 InRelease
> Hit:5 https://its-pointless.github.io/files/24 termux InRelease
> Ign:1 https://packages.termux.org/apt/termux-games games InRelease
> Ign:2 https://packages.termux.org/apt/termux-root root InRelease
> Ign:3 https://packages.termux.org/apt/termux-science science InRelease
> Get:6 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]

Uninstall game-repo and science-repo (`apt remove game-repo science-repo`) and then switch **all** repositories to another mirror, not only the main one (see [first screenshot](https://user-images.githubusercontent.com/18900601/155493129-513cbc55-cbe7-4452-86bb-c45af9544722.png)).

**Comment by macerg** [comment]
Thanks for that. Didn't realise you could select more than one repo from the first screen. Dumb me!
Fixed it.

**Comment by angelog0** [comment]
Upgrading I get these errors/warnings (also using your repo as described above):

```
Err:3 https://packages.termux.org/apt/termux-games games InRelease
  Could not connect to packages.termux.org:443 (127.0.0.1). - connect (111: Connection refused)
Err:4 https://packages.termux.org/apt/termux-science science InRelease
  Unable to connect to packages.termux.org:https:
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://packages.termux.org/apt/termux-games/dists/games/InRelease  Could not connect to packages.termux.org:443 (127.0.0.1). - connect (111: Connection refused)
W: Failed to fetch https://packages.termux.org/apt/termux-science/dists/science/InRelease  Unable to connect to packages.termux.org:https:
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
```

**Comment by Daofang05** [comment]
> Thanks for that. Didn't realise you could select more than one repo from the first screen. Dumb me! Fixed it.

Plz how dis you fix yours..
Non is working for me

**Comment by Grimler91** [comment]
@angelog0 `apt remove game-repo science-repo`, those repos are empty and can be removed

**Comment by angelog0** [comment]
@Grimler91, thanks!

**Comment by TheASVigilante** [comment]
I tried what you was written here but, I can't switch repos either though because of this error.

>W: Failed to fetch https://packages-cf.termux.org/apt/termux-main/dists/stable/InRelease  Something wicked happened resolving 'packages-cf.termux.org:https' (7 - No address associated with hostname)

**Comment by Rehan587** [comment]
Still doesn't work with the given steps 😕



![Screenshot_2022_0306_122147.jpg](https://user-images.githubusercontent.com/84271835/156912564-8a94f1bb-d216-4044-86ce-6df4ab7214fd.jpg)

**Comment by mi007d** [comment]
> Still doesn't work with the given steps 😕
> 
> ![Screenshot_2022_0306_122147.jpg](https://user-images.githubusercontent.com/84271835/156912564-8a94f1bb-d216-4044-86ce-6df4ab7214fd.jpg)

Same here

![Screenshot_20220306-035017_Termux](https://user-images.githubusercontent.com/100167438/156912521-f0b7ac2d-b6ee-4405-90f7-23bd94941cee.png)

**Comment by macerg** [comment]
Rehan587 still has the games and science repositories included. Delete them.

**Comment by Rehan587** [comment]
> Rehan587 still has the games and science repositories included. Delete them.

I'm stupid sorry 😅

**Comment by Grimler91** [comment]
The repo behind cloudflare, packages-cf.termux.org, should work now, but there is still some issue with the proxy we use for packages.termux.org. Have written to fosshost support again to see if they have an idea about what is going on.

**Comment by GitHubax** [comment]
I am having a problem with installing package x11-repo in my fire tablet.
I had installed the termux-app_v0.119.0-beta.1+apt-android-5-github-debug_universal.apk found [here](https://github.com/termux/termux-app/releases/download/v0.119.0-beta.1/termux-app_v0.119.0-beta.1+apt-android-5-github-debug_universal.apk)

What I want: 
To run x11 on my fire tablet (fire 10 HD 7th gen) to launch some remote server program and also display the program in my tablet to control it.

Problem faced: 
On running the command `termux-change-repo` , it returns `termux-change-repo : command not found`
On running the command `pkg install x11-repo` , it returns `E: unable to locate package x11-repo`

I tried following multiple related posts but the problem didn't solve. @Grimler91

**Comment by agnostic-apollo** [comment]
`termux-change-repo` wasn't available in `termux-tools` package on Android 5.

`x11-repo` package does not exist either or the x11 channel on our main repo for android 5. However, debs should be available on archive.org in the `termux-repositories-legacy-24.12.2019.tar` file. The package dependencies will need to be installed manually if using `dpkg -i` to install debs.

https://archive.org/download/termux-repositories-legacy

https://packages.termux.dev/

https://packages.termux.dev/termux-main-21/pool/main/x/

**Comment by GitHubax** [comment]
Thanks, @agnostic-apollo, for the prompt reply!

But I still have a few doubts:
> The package dependencies will need to be installed manually using `dpkg -i` to install debs.
What exactly do I need to type in my command line?

> https://archive.org/download/termux-repositories-legacy
Hell a lot of files! Which one?

> https://packages.termux.dev/termux-main-21/pool/main/x/
What to do with this one?

**Comment by ChiefMikeK** [comment]
It's best to ask for help on [reddit](https://www.reddit.com/r/termux/)  more 👁️👁️'s 🔍 on
- Be precise when asking for help
- what android version? plus mention fire-tablet version
- what x11 desktop? plus gnome, gtk, kde?
- what exactly do you what todo ie. ftp a file? backup a directory of files?...
- ???

**Comment by GitHubax** [comment]
> Thanks, @agnostic-apollo, for the prompt reply! But I still have a few doubts:
> 
> > The package dependencies will need to be installed manually using `dpkg -i` to install debs.
> 
> What exactly do I need to type in my command line? What does it mean by package archive file argument?
> 
> > https://archive.org/download/termux-repositories-legacy
> 
> Hell a lot of files! Which one?
> 
> > https://packages.termux.dev/termux-main-21/pool/main/x/
> 
> What to do with this one?
> 
> Edit 1: I want to remotely control a RHEL-8 machine (gnome) with x11-forwarding and not via vnc


Is anyone here to help me regarding this?
